apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  labels:
    app: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:2.35.1
        ports:
        - containerPort: 3005
        envFrom:
        - configMapRef:
            name: audiobookshelf-config
        volumeMounts:
        - mountPath: /config
          name: config-volume
        - mountPath: /metadata
          name: metadata-volume
        - mountPath: /audiobooks
          name: audiobooks-volume
        - mountPath: /podcasts
          name: podcasts-volume

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

 
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: config-pvc
      - name: metadata-volume
        persistentVolumeClaim:
          claimName: metadata-pvc
      - name: audiobooks-volume
        persistentVolumeClaim:
          claimName: audiobooks-pvc
      - name: podcasts-volume
        persistentVolumeClaim:
          claimName: podcasts-pvc
