apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Home
    theme: dark
    color: slate
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Dev:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Media:
        - Audiobookshelf:
            href: https://audiobooks.rahatahsan.com
            description: Audiobooks and Podcasts
            icon: audiobookshelf.png
    - Productivity:
        - Linkding:
            href: https://links.rahatahsan.com
            description: Bookmark manager
            icon: linkding.png
        - Actual Budget:
            href: https://budget.rahatahsan.com
            description: Personal finance
            icon: actual-budget.png
    - Monitoring:
        - Grafana:
            href: https://grs.rahatahsan.com
            description: Cluster monitoring (local only)
            icon: grafana.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "pi-zoro"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
  proxmox.yaml: ""
