apiVersion: v1
kind: Secret
metadata:
    name: actual-budget-env
type: Opaque
stringData:
    ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB: ENC[AES256_GCM,data:Jxg=,iv:mLtp5sKvI+jt+5ujeVHnYQUJSupSimw+6ymE5viCqLA=,tag:U2y15J1dcljIoDZGdibpjw==,type:str]
    ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB: ENC[AES256_GCM,data:d84=,iv:mi0x1eGnoaNcmzsJZnzAbWYWXp3nRgXDva5122ekwyY=,tag:sTLyazqSA652GDpjIbeVRw==,type:str]
    ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB: ENC[AES256_GCM,data:RQg=,iv:oJ1ZY0IIWEZECZPA55W98zoGUcs6FQ4AdT0YkEnFR6A=,tag:vneGM/FiMaVtv3ddf+MKFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZW9ONVp1eTc4c0JNNnVM
            RVhnTXNxZnN5VVhaellBVFdka3JaWHErZjJVCm52a1luNWlSK3U4amliYVpSUUQ5
            RWRuWUNQWlNEc1R0cmYyTTVlVTBVZ0UKLS0tIDhPRGNrZVRhSzVUOG12KzZuMElo
            ZkNOOStSWE9TY0liLys1UXZINHcxQnMKy+S2kZPwlL2Jpu6s/7nF6C1u4WQgpfhs
            mYrESwAJjBhdHLf82wqRpOiKAB5f8oEv+kg3tjJeS8fiQjkW+LlsyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T03:17:00Z"
    mac: ENC[AES256_GCM,data:BkoVMu4v9tTCk42XggG/cpb1lXZABv0upebZt+pagt9pp84+sDfN8Js+uuKe2lx+iOWeu/ZgouPbI+eZa39uKA/DaRRISrmMF0a0sCq0h8EmOmoC1Hc9xClI7dd70ZSEV6Z6fQIGZy8Fj6G39GOajX9OqgyjquP1K67EArvDS4Y=,iv:lt+tR1r2fR47K4/7DGAVD4txF/xFjRQnXiLnTbPhKXY=,tag:ZGNJR1zFjOA8vTAGManRQQ==,type:str]
    version: 3.13.1
