apiVersion: v1
kind: Secret
metadata:
    name: actual-budget-tunnel-credentials
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:74O/7y4OyezUTtYGY5RjZmWp2V7EnazwldVkd0gF7DkCC4qP3qYfW4zjukitUoz0PlYpRkEj+Yw1Oe/Ylupslp31DmblpLA/Iv7qTOkYhudhfcvlxlpK24zzrPS/T5bXWvxFj3pFQzlFqDcvBOd4rU9p9QjQUPZ11bdZgSh3d7EREPqR5jLOrQYUFW45e6DaNXBXMzxhruipxNQhj2EbI6Z7cW+pBIj1G3WTv5HF33Q=,iv:vijrCPqdXg1+X6X/rF2S32+KTOOQz8i/dZWuF3I3ivg=,tag:JQjemGcif8DuMf18UtFhiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcTZXZFpTbUV5d3BCQ2JG
            eVV0ak91cGJ2SjAxYUxUV0VwUjFrNkdxUndjCm56RVhCcVdrOVBCSTBBTHY1WGg4
            OEI0aS8reXJlSHZpYVNCamJSNWtGdmcKLS0tIFE4emMrMkM3M0FEem1DYTJRVURr
            TWJRMlRkZnZiUHpPeUJ2N3ZMeWZQUE0KIP2FZmzNa5oj9MvYjlMqeyU1IlFDsfZu
            x69jeNYzq2810ZrKPzxyEs4bR78V2KU12oZ15JR375NKefrVF5SZ8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-20T03:17:00Z"
    mac: ENC[AES256_GCM,data:J8TvZXpet38GqqSkZ/pmGdyBAbDSvVGEkG0ybN3Yppm7+XouZ2OYS0TV3+NaJQuxQtxcEkM+8Q81OmkVU24bccQLGBnUBk+6wEe7WnEBfffKsTk+SwxOCFj2LCQmu0ZySTi+SOXzZTzInsKx5TGgAYhdHhFH3RRZFk1sKPn6r20=,iv:NrhU3j4MGewEt53k57Ez4aNILbrUhqkMh5pn0BXOyag=,tag:fUkHswdw3W4agESDam0/uw==,type:str]
    version: 3.13.1
