apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actual-budget-prod
resources:
  - ../../base/actual-budget/
  - namespace.yaml
  - pv.yaml
  - actual-budget-secret.yaml
  - cloudflare-secret.yaml
  - cloudflare.yaml
patches:
  - path: patch-pvc.yaml
  - target:
      kind: Deployment
      name: actual-budget
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
  - target:
      kind: Deployment
      name: cloudflared
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
