apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:d4GLwlPxWNSfw0+Ns6uxoR8pxdS/DCLUTvSWhcQUy3zL1UUwmWC32/pDSdv8Znr2rzdv+Ofo3gqAJ0IU8vKrDWqIqz/vPgKEB2PfTOCosTPwH4f36dHAfQJ6CDkQL7MasOCwIIy/oX0m97Jyy3pfoS7hm6+EWc7Vagp5liISqmfScRLIrozCqbgebeUMV7+LdnGwfTmAWSk4a9wD+e9zC2LIG/ai7eaEbGwOzd14ZnI=,iv:E/2pCYHdHXInXRSn5s4v4I2xkbZhFR1sJJR8mlePCUE=,tag:Xsd0E+rPs2HGaTSTa8h6Uw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUjExMHJPN1ArOVJhWEtR
            TUJ5VDFpQ1NoYktkMkVkWjlscWJaWERzaENnCmo5aEZYSGdPQzY1VlV2L1dIZmVn
            NFc1VWNMdVk3S1ZIcy9UckJVR1RoZDgKLS0tIEZTOHpRcmFOcHQ2RktBY1hHeXNN
            dFdSSG9TSzdBSVYvdENWUHIyZEZkKzAKDyBNLmeRJxzaiXRZhdsVgxW+ANKwXVqT
            fjnwwfLytGvbUO0aplk2PTRlxzMFtmEDDsjMITIaFt12OMEoOrCPhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T21:16:47Z"
    mac: ENC[AES256_GCM,data:edPna2DV/4+rw8tQ1BSlC+iiOamBhUZW9zuhA4CMLyY43sR7YszW1GtTDR8Wwj1DJ09to5odMb0qb3N28C8hm6kzsI4TyhTbKmARAK0H3EJY6mVPxt4f95Hukl0OUmltDSuOTev3fvD9A5A1w/pYBOOkcBpJWe1oi59Xq/+NZsg=,iv:bhnOWE68rjnMC4+cKiQri8qZJb40QtSRWQmhDtlQntw=,tag:nl7d2uT3yg2Rz2Ma5z1wvw==,type:str]
    version: 3.13.1
