apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf-staging-ns
resources:
  - ../../base/audiobookshelf
  - audiobookshelf-staging-ns.yaml
  - cloudflare-audiobookshelf.yaml
  - tunnel-credentials-audiobookshelf.yaml
