apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:JtTVZBBZXcs8Z1WwFsBtkG3+bKJt0ZEFrIug91V5mVeYo96fmUF15t8Y/lC5e7XCyccLdoVqGAsJup9XIuERQvSszFMV4O401QFPXs3850kZ45MKKoSexSoKGQbmN38JXmfhjAyXtDsJCHF7yPMComJRthbq04e5kOZjV8UMDzjvfBgOgnWAUOoYvXdl8acvwhI3YsJCgNWDLFx20aSxWxZQp6OChibiKmiv0AKqeCbJpgin8DVpuR2x3bHrACpSVKhdU/oShtfdbNnUk2PDMPL2LCaSJuJPZj9kYC7dzVRQNlZ6rDZm8zSn0L4=,iv:fNWXa4Y6ggosTTsBGrKo1RxPzMs7y1O/OCGfdXR1oTs=,tag:pf8Nreaeb9r/L0qvM5J8uQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials-audiobookshelf
sops:
    age:
        - recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Yjh4b2FqdkxDdEIvZ05I
            cG5qUzNjUmszN2wyN1gzdk9uUmI4S0JEeFNFCkd4RGZXYVB3SjNyNG56a3Z3aUhs
            R201azk5WlV0MmcxcHhFMUdVZEdRcHcKLS0tIHl3bnVieFU0Wk81UTkrSXAyV3Nx
            Wkx6ZGg0WGI0WTFSdjFZdVRjWm4zMVUKeIlQQy5o1fZz4fUZWK8yOh9H2bVU+EP2
            +l5n80FTdlNppgp+l2PeRcn7Qt90dYdoiMvjUVQslSDfcFzcMwgmdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T02:36:35Z"
    mac: ENC[AES256_GCM,data:Wp7E5CpTz/q73ttQK1kuI6M+zVJCgg/r0D29p8qs032++AoplqpBmPBj0kVLI+NtlIvnG+5Ltzsw+QMszEUj0nNxRCE0R4wIrJn7VljCURZgRYEbBHodtDPSIgEWvCJFZprAKurXhE9MPixzcjm6yWUWwUe9/V2XWmKYrVA7Xm0=,iv:SMGLi0lHEE5GrR4DWz1sDKFxyQ2aj1t/4/BKWnO3f+g=,tag:70sY0SnzJNtKIA8Xdjn+vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
