apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf-prod
resources:
  - ../../base/audiobookshelf
  - namespace.yaml
  - pv-config.yaml
  - pv-metadata.yaml
  - pv-audiobooks.yaml
  - pv-podcasts.yaml
  - cloudflare-audiobookshelf.yaml
  - tunnel-credentials-audiobookshelf.yaml
patches:
  - path: patch-pvc-config.yaml
  - path: patch-pvc-metadata.yaml
  - path: patch-pvc-audiobooks.yaml
  - path: patch-pvc-podcasts.yaml
  - target:
      kind: Deployment
      name: audiobookshelf
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 20m
            memory: 80Mi
          limits:
            memory: 160Mi
  - target:
      kind: Deployment
      name: cloudflared
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
