apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcasts-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: audiobookshelf-podcasts-pv
  resources:
    requests:
      storage: 10Gi
