apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: audiobookshelf-audiobooks-pv
  resources:
    requests:
      storage: 10Gi
