apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobookshelf-audiobooks-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.153
    path: /audiobooks-nfs
