apiVersion: v1
kind: Secret
metadata:
    name: democratic-csi-iscsi-chap
    namespace: democratic-csi
type: Opaque
stringData:
    node-db.node.session.auth.authmethod: ENC[AES256_GCM,data:KskrVQ==,iv:LdsA5OQfjXW/o/ucW4gPgx/CM/Z/n6nhSyNlBrBlYJo=,tag:sFGI8OeU6ZcGd3Brb+pBhQ==,type:str]
    node-db.node.session.auth.username: ENC[AES256_GCM,data:t04VBcCKugFAatQJXA==,iv:A/sMrfVQfCHa9GTzhA34etmCGBib3Cd7OKg5rYjooGI=,tag:3mUEJq6IGivRNyHtoV00uQ==,type:str]
    node-db.node.session.auth.password: ENC[AES256_GCM,data:bt+DA6oGJ5sllMKTFmg=,iv:QGunBB2cxM5U4yfZ3b7MuUqhPS1Gq5izMhoUiBNviLQ=,tag:GJp1EyIL5DVXgy0zzISpEg==,type:str]
sops:
    age:
        - recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNUMzdmZDdGdmcXdsZGto
            VHFQSG41dWxUNkJDdnZEY2lyU1E4aFV6SFg0CmpJcTJyZE1tbzB0QWgxb3ZuTFVJ
            bnZNKy9mN2s4dVhnd1hnN1hteU0ydVEKLS0tIHN2VUMvRXpMRlhhNy9nRUkwRTF4
            TFpudjBBNDhRK1paaklwZjBNb05FTTgK3xUusc1C2aKZu86VImfDO4UWsXDzySFd
            rzbAqXS2GsWJLp9CgDB3LEj3A0heyopy+IwR2Cwy8FyMx1jDvPV7Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T01:01:49Z"
    mac: ENC[AES256_GCM,data:BWPmfpE5hG8/1xKsaxsH/9dltcHpuvCjs9I3zZCbuj2i9LMhPjXptwIx+jTf6qZWrbryFVb18wa+csg4S+tYP7TuLxcVaX9NVohnQ/AYmh3LM1t+ElI1GHj6cdvfpWcWC6OdJ1/RqfHYQ9tWBKmB6HJs0pA8qvPiiGIUhOQDFmY=,iv:qCiiK0isGLYMD4bH3FjFFfwIRQCb5k3gUtdJ9xJlUoI=,tag:LcS0W4GaZqolSLRRGlRXGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
