apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qnap-iscsi-manual
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: org.democratic-csi.node-manual
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
