apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg
resources:
  - ../../base/cnpg-cluster
  - namespace.yaml
  - pv-primary.yaml
  - pv-replica.yaml
  - secret-superuser.yaml
  - secret-barman-s3.yaml
