apiVersion: v1
kind: Secret
metadata:
    name: cnpg-barman-s3
    namespace: cnpg
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:YXurlIhJlC7R3V1mdyFsRVksa0M=,iv:pwCtGY4WTXJ5SJX1Ncm3hA4Db4TYkYflvE/b30fmeqM=,tag:ROozsOedWcuZ90jKTsVJ4g==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fsG/i/blFRisMmyXFFbHBAh0OQHdY2ZBUK9Zfyww0UYukfmae+pdFw==,iv:aDuczXEBAON1nwiIlRLtupR//8ikb+VFyvFsNP5lh84=,tag:BiZsiufz014JO2lSjDJEJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaHFwRC9tSS9QUHJ5bERG
            cXpMVngvd2ZkWDdlYVZtVjg3SUpQM1JscTA4CmQ1RDREWTBPTlpveGV5V2RrWU4z
            MVBHOEQrc3NuRXpBQVROZEtOYlNEM1EKLS0tIDZ5N3pLMHMwWERGeHdhS0pkUUJn
            VWRBNjNqUkpXYmtHVnNQYkI5UCtodjgK8uBc73dUY3ZcJt1IjjlL25Qw9yiI7yOd
            zN6stb4rgZCw98IMC1hMIX0HAWv/l4GnkNrxnLAOTDYTnQmAPX3a/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T21:32:35Z"
    mac: ENC[AES256_GCM,data:y++TBkziMSHZ6FNiMUBi8SAthczsV+ZlE8vYhwBocvwYgP9QCo8mM3jCklZQm1vu5RnzacQKG5sTBUBDn5joXfigW/goWYr/gCiQjtraLjAoppRHLP03JKYwRzvXOkXTqWhBWOCzOF+JQIUwBuGNz6Mvdgb4l7QFJJgpUtboUWk=,iv:YHtEA1v2P5QwctPg4MM9HNkvpPZAN4VxdhsACP8Zkwo=,tag:iqXqD86igJ1U1tFcCpenig==,type:str]
    version: 3.13.1
