apiVersion: v1
kind: Secret
metadata:
    name: cnpg-superuser
    namespace: cnpg
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:IOemmZR9qB4=,iv:9I/Ll9tUq0fPkGnccT0U6F/QcEGZ7BWGiOktjJvI7wY=,tag:DlhlRf7vjmDEJFcbUHbgOA==,type:str]
    password: ENC[AES256_GCM,data:LyPk3PuoPkOdwvUeyHDI,iv:wCbZsVTtnzVqff96L8yYwm+bLCNT++zdrbWgepmh0ZE=,tag:CzB6oYdKTdmrQ81H/DlvnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZXhQdnhMNDhZWWk1T2Vx
            THJEZXZDOHdTUHo3MWFjRXRqd3JudmJOakZJCkhtU2o1cmVvQ1dnUDAzaytOZDhp
            c3p0a0YwVVIrUzE3WGcxYXZpdmhadkUKLS0tIEprNU1TYnNYNlNQNnZnTmY2TzNX
            Y1Z3OGg0UU54M0FpNnBoUU9FOTFCZ2MKJy7HO4Fv2ecpIEo/yiqywqfY54ucr+5a
            DtrlOM2V20MudOjOeD953TuBsiU9RB023zfgGuhB0QCFOIhtd1KvZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T21:32:29Z"
    mac: ENC[AES256_GCM,data:65xlpnOXvAc1kbUjlndfYiFY0GXWeHFRu8Mqcgasmdq9DDGTsCykSNX7SfKET7Ora6jC4S85qJBpFe67vP88CN/UH9Vxf82bhpreiTE3Fkx/NWI1V2g2lGlF/MrB/I10NmCej7QUIAFuURrgdb8rA6hCWSrzEDOklGydPuQ/rK8=,iv:Z8UzbYNZXbz5xbfv1oeaALnK4jvMSXV7srURfO8Pu3E=,tag:AWdbCUGO8KshZ0SXb0Fntw==,type:str]
    version: 3.13.1
