apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding-prod
resources:
  - ../../base/linkding/
  - namespace.yaml
  - pv.yaml
  - linkding-container-env-secret.yaml
  - linkding-db-secret.yaml
  - cloudflare-secret.yaml
  - cloudflare.yaml
patches:
  - path: patch-pvc.yaml
  - target:
      kind: Deployment
      name: linkding
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: linkding-db-secret
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 40m
            memory: 180Mi
          limits:
            cpu: 200m
            memory: 320Mi
  - target:
      kind: Deployment
      name: cloudflared
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
