apiVersion: v1
kind: Secret
metadata:
    name: linkding-db-secret
    namespace: linkding-prod
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:gSYe68/pQlK9SRKu/ECXCesLVDxDRwgy/5wK/vRJl3jrqcZGwiGzwLAJvlN05FHOhealbtQulT3/QJ9R0MuTmroXEn7eq00/vQvbQwdVlZgfOdmi6WzRZmEi,iv:Z0UlFOysnzOLAS+LurjteIItYLAgfd3sR941k9awdNo=,tag:EJ3ef2Vx0NM/Nmeaz9+VCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cnI4ZTJFY2lZRXVqVzVE
            aEQwM0NXbU1ORzgvTnkrMVh0aU4ranR5empZClp5VWJxZDl1YWtEVG5pZ0hJYjc4
            dHp4U0R5cXpGcTFVL0Z4WHFVc016UXcKLS0tIHJia3d1YlNabnlCcFV2SkZVRkhT
            ZW94NG93VVZybFgyaFdwZlBGalBnSk0K2u7N1PQanTvbZ/KwfEHGtxOJBkkW43GO
            mevO1SNuq5eNI24QfQoH91b6OMd2u1ZJ5mnFhMcpSPcAqZ1u4uTDlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-15T03:00:02Z"
    mac: ENC[AES256_GCM,data:19q1H4GeCWFA1Q26nKsUJoLjGf45iUCwV+2CEk7t2x4k/tq4YaCQKdFGMXXI02b8bSyYXS5XEBHOtTo8PkOcrFGRDLTJBsf3o6WObPMHComrvXnHbA9/W0O1RBNormNF/W7XGsn5OcBzMg44CHzyWhtSSocaPMaUO+htnbNyDF4=,iv:n72VCvDCNnkCuF7FnnCEbtr5tYx5LMbwWj+GHXfcNGQ=,tag:WjcjHultJGxunub/odQ4wg==,type:str]
    version: 3.13.1
