apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:qY6DLRNRsRo=,iv:ntF0XsEMDNDF/MHmQX/NBjE/9mPm67MgcHDnXiZb66U=,tag:tXC6405NadWngARgc9AElg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:ZSbx7DX3NoS+0KT8,iv:YKOjNQi51qlTFK9HOgjXQkzXoayq+vH7v1DGO1gDKHM=,tag:6FpIhWkmTURESAr9S93MFQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSUVDdXFzaC9nTyt2dEZZ
            WDNnYWxOQTk2bnlJUFdURTlSNDUvWERQT2pzCmcrbVEwV0Vib3JkY01QbzF6L3c2
            YSt6SUcxbXo5NkpNNUg5Y25zaHhlRVUKLS0tIFQvMXZVcHkzMnFIR2s2ZFBWZVBx
            aWszeWd2RHNOUVdWbmNxeHNicEJSU1kKGty4oTYhjfRkm/rBc6hJYwnjrBRsFCOC
            vmEYKPD7NOz0oxqt+IV4ceS5/QO9slX4Pq2SqP/5/4TMNu/lI4l+Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T00:49:05Z"
    mac: ENC[AES256_GCM,data:Xe+qtdHArBxNUiy+/olFTNwlEwBOCJWBWGaLaKWweMVMnZKUKFsFgo2jA6u/dtsjsZAuNrObKHc6gLdjRQjrcWyLyBjmlbNsq33WUl3dveTXn8coYHeynnXgWXD7N7loqgqBT9pXFTUE8h11IE8s0WyqrqTx7pSV94n8sCJmtP0=,iv:BIauk7P4DEcQbiJ14rgUYJSVE3szgWwEk/VQxqmQTCI=,tag:BlVoNgvzp5HWXXEF2CG/yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
