apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkding-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: qnap-iscsi-manual
  csi:
    driver: org.democratic-csi.node-manual
    volumeHandle: linkding-data
    volumeAttributes:
      portal: 192.168.1.153:3260
      iqn: iqn.2004-04.com.qnap:ts-464:iscsi.target-0.88196c
      lun: "0"
      targetPortal: 192.168.1.153:3260
    nodeStageSecretRef:
      name: democratic-csi-iscsi-chap
      namespace: democratic-csi
