apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-webhook
    namespace: monitoring
stringData:
    webhook-url: ENC[AES256_GCM,data:9qeDVHcCIXcWlU6acRN2VQriwSwJG6b2g7WMi4cpEJal0oWopiXKloziYg8S9p+c0CVUHP9pGv1owtVDCYOSXTVWvrYqggqcpXtW1eXu8fBw,iv:dDLew4aqMZ1YxalAvo7Ik0mE7IIXuXjJ/Qiqz5E+5EQ=,tag:L80WZcgpddYIAb52Ki67pA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d2Z5aGxUaTNpTjNyb0pi
            TE9xLzBOYWdIc0ZzRFdaU2xTNUk4Qjc3S0hjClR6elQ2ZzN5UWlNNU9Id3NSM0xa
            eWpVVDA1SjR4UW5wZE8yWGZYUHRDcVEKLS0tIEtTdTZxZEpvbXZmUkZPWi9pUEUx
            d0huYUd4bHFVeXF5K2RXdFZ5OENIT1kKjwO8ZZwtvFP3Vus/hYdwZ4MPYgkANuP7
            YT5khLN5va1jhGCWuzgrBWpDWTl68oqvr5ogxVjlq2mEy8KAMxlX7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T05:00:35Z"
    mac: ENC[AES256_GCM,data:C2FQmSfVRRWXfnyIKHC10t4jNcSum+4h7h+IX7P1HkRQygpDqKkKXdBi5uArZ4kBTlY4GoD6odElW1yi4ZeZUObog0PoT9BJAjCjtN2uvOvZu8v/UtHXCApR7yc4tPXJnoTaX4PIFVdkoGK1BgkOBsALj9BCCKbgdBBth8e90tk=,iv:YlbqZyPvwrW5xi/9ipiznAz917PBd30CSYQhM+bvdMY=,tag:c0bsXiUaGRd+MeDZChVxPA==,type:str]
    version: 3.13.1
