apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-webhook
    namespace: monitoring
stringData:
    webhook-url: ENC[AES256_GCM,data:Gsq+ySj+WiBM3hGNdwDNapyqX/AU5JMaS5tJ58MXyVTn+6Af/8P/nZrsQ1MkqXVoVALNKTyEpUbt1cO1wDESoAQRxtQ6npwuYFjHnzIPFx7f,iv:fYRT5scwD4EiVfiqC+TPp75Btj9a3vdu8QcyJ+7D/JU=,tag:hdeLCOKeQsrCMThwEyy6/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RS9vZUtRemhzRVc1K0xH
            RjZlNlpaYmZGRjRITGdMVjU3OTl1VFg0aWl3CkR0aW1tTFdFMS9yL0tzRnRvajF0
            bDYvSDZQd1VnMWJiWGFzZlRiNVZjMWcKLS0tIDhZNWF5L0dnK0xVeXIzSTZkUEhQ
            UE9ackU2RHNIVW0rcm5KUFFudjRQMWcKM0sQkKjXb9qkPJDGKRFQtCDCkEWF50NP
            9Q9Lpjbyf62chnNkGwgXihPuHHtHIpZGO4zrrBUr7cA8J2jlDd5wZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T04:34:32Z"
    mac: ENC[AES256_GCM,data:e2NphRe7bBRKzLMu1u+2eqM9Rgjiy9dWp2gckCg2hOvbxgGcuDVW8A4wxgwQeeHkVPr3HBXyfRv+q4uHQ+Ojmxz4u4zUG8IhcK5A7N2qQHQHPsUVsSd5eq+BM1VNS2/I8krGQ3VdZ9XOOyfnvyDpVAKiN/7vf1mv7x+4THWqVlY=,iv:G4CdSKzJYONaEkcOTbDSvceNM5ewbLcf8YmIn1NnmzY=,tag:V4pJWESRVyow98lQ4Xc04A==,type:str]
    version: 3.13.1
