apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-iscsi-manual
  resources:
    requests:
      storage: 1Gi
  volumeName: alertmanager-data-pv
