apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: qnap-iscsi-manual
  resources:
    requests:
      storage: 2Gi
  volumeName: grafana-data-pv
