apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:VaL9oCwEwLR0JAbGK6jdvLN8sFy7TilX8nkUoyw9qPgEqPGFjhQPEohb03ucHW8Z4B15GfPieUB85KDB6WMzecTKHtiPwPDk4/CC1YhetuTDVCVxvfYZk36vd1nmDc1SAAGOppdS6qh7Zjd7CARAwoaugq2Vh4miC0hhjtziPb2Blh5eeaEARzOdBnuZPeet7EEvwSUyPJkAXIzyLMnCc2cgm47dFyUgNbBbrHiyb40q5Uuykxa3Xw7HJn4KXCoqo1UeihOHp62V31vHg8cmplTdWexsqou2A6zL06g6x9Tq5DlfENGLCgmXQAw=,iv:C2kJ9aIeWzWOuLs0yHANBWy4mmo+LCEskV5ZG7dmjy0=,tag:+Fl+7bGnju0AmufCgiFzWw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLV2dPUWFXRWs1OUR5MnFV
            ZGlUNnhaRjZXUkhyTkY1NzhuT1NBbW9yRFMwCnJmdmR5dGVrN3hrZWppTG5zYW4y
            UXhIakl2RG14ck9qc0l0Y3JqcWJiMFEKLS0tIFNxUEI4MTJoYmFLTk4rS1NlTlov
            WTFXd01uNUVJRGVobHJndXByd1BqUjgKKrDw6wAd6WYpNzcMaUO8BcXIPKtIt1e+
            euFSwSBd//LM2sE+6nSqg/UX9muhnWYjQMc2ga0ne78O7Le13N39Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T02:53:58Z"
    mac: ENC[AES256_GCM,data:unKZIsj+7nKzTW1LUtR+lTbPNAxSZDlmxf6Ok/pTxvcCLpAhGCWqs9jABlyNLwN2zQBjTzbt9TvyQtB1iPdhGcny4tSGwfmZhJqjiMqRmnmBKh0Cp2+89oYvjuXpMoRgAJG7GsLH8gTpLZwaxdWAquitaWf7jSgasQgL/ofGb4E=,iv:CvDM0FaqTbi1aFz7H3p6FXh1UIyHMHNZ4Xfy/v2bUBA=,tag:1I8p26mmmBPLw5jGa1k/5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
