apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/    # hops up two directories: staging/linkding → staging → apps → base/linkding
  - namespace.yaml
  - linkding-container-env-secret.yaml
patches:
  - path: patch-pvc.yaml
