apiVersion: v1
data:
    password: ENC[AES256_GCM,data:+vzYZ4U0rgI=,iv:oLZw72dxcwgnTwAAMlXwby7/Sl/Lf+nP8/RxJzSJKV8=,tag:+4peGpaA322uYIhH7s/bmg==,type:str]
    user: ENC[AES256_GCM,data:7ifnY+kgqxA=,iv:AaqT0WqYWLCkJJZKlmouYjCJnVieeVNEs1c2naLy3S8=,tag:Ed/+4QHp7HmKNKLtBkzSCw==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNalRsaHdZYTFNTlV1VW9I
            Ykt1ai9lMENXK0MreDhHQmJLZE1iZVB5emtZCjNUcWI2azhmWTMwNkNuVmhBWmVl
            eTF5Z3pzcHJNMjlvblF0cTE2dUpFTHcKLS0tIExVZDE0bk5iMUJkeXRnWnowN3pO
            MldQa2RIUkZSV1g0NHI0eEtMYkxaQ2sK8guZK1IQQ0DPVv3O0S5ey1gwQxACBJmT
            3ynWj84SU6d8z5RNe+LE1w0CJ5SyDaMTVjfcU3YfrjBfdBXnvJj31w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T18:47:43Z"
    mac: ENC[AES256_GCM,data:2adk55kItgY/I6YArbkhfD5j512Qk/nSUDfNTZf3e0Lv+AA+CWWp37pxr9JRXte08OA+kLTfjpagTB3KwhgYC0thCJUCvJbo3y7dSCTpsRunIWYaPF1yi7WZbLvycLdaB1O2j5tQKHrACqUCGOzLyroFVF4qmXiKVIXMl6QuYB8=,iv:mRgNCky/e+vyoeke9fv3aoKA8onrMCPONFCkSdP9sGQ=,tag:/XXr33rZgKoQqh+nF673IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
