apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:D/UpZ3qyRd8WQPxhZ3rPL0LvrULlDM09XMJmeiBC3Re5WVEBOzsfeCArjeJ2zwwOArLdcSEiI9c=,iv:cNvGTsPKPU8g73jadfy5z752yQdg6nCdCb4+TQ8Wm5g=,tag:3Z7iFExjc5jK3LrhO+Km/A==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTE44RkpTb0pxb0oyenpU
            ZXU5bEpuODdGSEdMclFLMjVNSjNBZ1dkOEI0CjIrV3BIZUU5cFhmaFBiWFg1ZS9K
            dnA2ZlJQUFhKN0MvbjYzN1FKeGdhZncKLS0tIHNNYThMbTJ0TkdrV0tpRWNkQnNu
            anN2L2Y5SUV0NmgyYVphenREM0NVcVUKGDylyevrnMYgMwZHj05sPWhmPpPpImT2
            NJyZdGoJnBOIACkFEaJpS3zYqkI7jm4CDHErTkIa1vPSHiZzaf03rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y5kcwc528w66sxjvfq4arpgtnrxmrjc2084mu54czmw2q0c3p3as4d4fpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T02:34:00Z"
    mac: ENC[AES256_GCM,data:yAlPWDU1JG8lqlivxz+CAVXtc05pB5hzZ9IS2Z6QF2IXBAfK/G3lstoheoP95iRFgRynesIevQIcNo4SLimIX6/dSEueC5sAspw9zxafaSOCEi6PiYCbr6v5Wg7uHONaFDHOxqINkdT3jOXLgMkALwxLtcum18pe4V4IuV3FqgQ=,iv:llF0VZOC5cdTDujaGdSi/KSWOQg/ZBqfbu3TgDCNw3g=,tag:d0tWheVslYHGl1eJFr1VmQ==,type:str]
    version: 3.13.3
