apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-cluster-backup
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: cnpg-cluster
  target: prefer-standby
  method: barmanObjectStore
