# Watches the controllers (installs Helm charts)
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./pi-zoro/monitoring/controllers/staging
  prune: true
#  decryption:            # Uncomment when secrets need SOPS decryption
#    provider: sops
#    secretRef:
#      name: sops-age

---
# Watches configs (Grafana dashboards, Prometheus rules, etc.)
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: monitoring-configs
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  retryInterval: 1m
#  timeout: 5m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./pi-zoro/monitoring/configs/staging
#  prune: true
##  decryption:
##    provider: sops
##    secretRef:
##      name: sops-age
